<?php
// hellogit
var $admin
define('proverka', 84);
// require_once "connect2.php";
require_once 'lib/connect.php';
// require_once "lib/request.php";
session_start();
header("Content-Type: text/html; charset=utf-8");

$admin = "admin";
$r = $db -> prepare('SELECT COUNT(*) FROM user_param WHERE id = ? and resolution = ?');
$r -> bind_param('is', $_SESSION['id'], $admin);
$r -> execute();
$r -> bind_result($c_admin);
$r -> fetch();
$r -> close();
if ($c_admin == 0) {
    die("Ашыпка");
};

mail(
"kolhoznaya43@mail.ru", # To
"Mail robot", # Subject
"Hello!\nThis is autogenerated message — please do not reply."
);
// $m = 'SELECT * FROM shield WHERE id_user = '.$_SESSION['id'];
// 				$r = $db -> query($m);
// 				// $r = mysql_qw($m, $_SESSION['id']) or die(mysql_error());
// 				$j = 0;
// 				$row2 = $r -> fetch_array(MYSQL_ASSOC);
// 				// $r -> free();
// 				print_r($row2);
				
// 				$r -> close();
				// for ($data2 = array(); $row2 = fetch_array(MYSQL_ASSOC) ; $data2[] = $row2) { 
				// 	$str = $str."<p>".$row2['nazvanie_zsh']."</p>";
				// 	$j++;
				// };









?>